name: cakeapp
description: Cake order app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/injectable
  injectable: ^1.5.3

  # Support generate for injectable_generator
  # https://pub.dev/packages/injectable_generator
  injectable_generator: ^1.5.3

  # Support generate for retrofit
  # https://pub.dev/packages/json_serializable
  retrofit_generator:
  json_serializable: '>4.4.0'

  # State management
  # https://pub.dev/packages/flutter_bloc/install
  flutter_bloc: ^8.0.1

  # https://github.com/Sky24n/sp_util
  sp_util: ^2.0.3

  # https://pub.dev/packages/either_dart
  either_dart:

  # https://pub.dev/packages/equatable
  equatable: ^2.0.0

  # route navigation
  # https://pub.dev/packages/auto_route
  auto_route: ^3.2.4

  # Support rest full api
  dio: ^4.0.4

  # https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.2.0-beta-1
  logger: any  #for logging purpose

  # https://pub.dev/packages/cached_network_image:
  cached_network_image: ^3.2.0

  flutter_lints: ^1.0.4

  cupertino_icons: ^1.0.2

  flutter_svg: ^1.0.3

  flutter_native_splash: ^2.1.6

  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator: ^3.2.3

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    -
  fonts:
      - family: logo_font
        fonts:
          - asset: assets/fonts/harlowsi.ttf

flutter_native_splash:
  color: "#ffffff"

  image: assets/images/cake.png

  fullscreen: true
